import type { Metadata } from "next";
import { Lato } from "next/font/google";
import Navbar from "@/component/layout/Navbar";
import Footer from "@/component/layout/Footer";
import QueryProvider from "@/QueryProvide";
import PathWatcherForHeroSection from "@/app/PathWatcherForHeroSection";
import "./globals.css";

export const lato = Lato({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${lato.className} ${lato.className}`}
      >
        <QueryProvider>
          <Navbar />
          <PathWatcherForHeroSection />
          {children}
          <Footer />
        </QueryProvider>
      </body>
    </html>
  );
}
